services:
  web:
    build: Blazor
    ports:
      - "8080:90"
    depends_on:
      - "api"
  api:
    env_file:
      - .env
    build: Python
    ports:
      - "8000:8000"
    depends_on:
      - jaeger
      - prometheus
      - grafana
    volumes:
      - "log_dir:/app/monitoring/"
  
  jaeger:
    env_file:
      - .env
    container_name: jaeger
    ports:
        - 6831:6831/udp
        - 5778:5778
        - 16686:16686
        - 4318:4318
        - 14269:14269
    image: jaegertracing/all-in-one:latest
  
  prometheus:
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus/prometheus.yml 
  
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana-oss
  
  fluentbit:
    image: fluent/fluent-bit
    command: -c /fluent-bit/etc/fluent-bit.yaml -R /fluent-bit/etc/parser.conf
    volumes:
      - "log_dir:/app/monitoring/"
      - ./FluentBit/:/fluent-bit/etc/
  quickwit:
    image: quickwit/quickwit
    entrypoint: ["/usr/bin/bash","/quickwit/qwdata/config/entrypoint.sh"]
    # command: index create --index-config /quickwit/index-config.yaml
    volumes:
      - "./Quickwit/:/quickwit/qwdata/config"

    ports:
      - "7280:7280"

volumes:
    log_dir: 


