/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

/// <summary>
/// ModelPrediction
/// </summary>
[DataContract(Name = "ModelPrediction")]
public partial class ModelPrediction : IValidatableObject
{
    /// <summary>
    /// Defines Prediction
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PredictionEnum
    {
        /// <summary>
        /// Enum _50K for value: &lt;&#x3D;50K
        /// </summary>
        [EnumMember(Value = "<=50K")]
        _50K = 1,

        /// <summary>
        /// Enum _50K2 for value: &gt;50K
        /// </summary>
        [EnumMember(Value = ">50K")]
        _50K2 = 2
    }


    /// <summary>
    /// Gets or Sets Prediction
    /// </summary>
    [DataMember(Name = "prediction", IsRequired = true, EmitDefaultValue = true)]
    public PredictionEnum Prediction { get; set; }
    /// <summary>
    /// Initializes a new instance of the <see cref="ModelPrediction" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected ModelPrediction() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="ModelPrediction" /> class.
    /// </summary>
    /// <param name="prediction">prediction (required).</param>
    public ModelPrediction(PredictionEnum prediction = default(PredictionEnum))
    {
        this.Prediction = prediction;
    }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        StringBuilder sb = new StringBuilder();
        sb.Append("class ModelPrediction {\n");
        sb.Append("  Prediction: ").Append(Prediction).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}


